### ISSUE TITLE
Singleton Unit Testing

### ISSUE THREAD

**Issue by lpzjerry** [patrickwang96/CS3343#11]
How to test a **Singleton** class?
- directly test instance
- create a mock instance (SingletonStub) with inheritance
Any suggestions?

**Comment by patrickwang96** [comment]
Dear Jerry and all, 
If you wanna test your module individually (without interference from other class) and you also cannot avoid calling other classes, you have got a choice called Mock.    

[I found this tutorial explained it quite straight forward!](http://www.vogella.com/tutorials/Mockito/article.html)  

This Mockito library could be treated as an extension of Junit. 

If you guys decide to use this library, perhaps we need to discuss more about which dependency tool to use. (Maven or Gradle)

PS: I personally perfer Maven though ;-)

**Comment by patrickwang96** [comment]
I'm not sure about what does the actual case looks like though...   This issue probably can open for discussion in a foreseeable long time.
