### ISSUE TITLE
suggested modification for real scenario simulation

### ISSUE THREAD

**Issue by SherlockQiu** [patrickwang96/CS3343#18]
The simulation of real scenario is available now in _Main._ It checks the whether it is ok to check into next brach _Order by Order in OrderPool_. If it is ok to do so, the code has to get the Branch it belongs to and then which courier is in charge of the order by some new _getter_s. And it will call the new deliver function added to courier to check it in and so.

**_Notice that: the origin implementation has no modification for current unit test but rather new function is added they are:_**

**_Branch.getOutManByOrder _**
**_Courier.deliverOneOrderByTime_**

**Comment by SherlockQiu** [comment]
so could i push it?

**Comment by lpzjerry** [comment]
I think it's fine to add the new features for testing purpose now that we have implemented the handler in Main.java
